# Generated by Django 3.0.1 on 2020-01-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyecolor',
            name='eye_color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Blue'), (0, '----'), (2, 'Blue/Green'), (3, 'Blue/Grey'), (4, 'Green'), (5, 'Hazel'), (6, 'Brown'), (7, 'Grey'), (8, 'Green/Grey'), (9, 'Green/Brown'), (10, 'Black'), (11, 'DarkBrown')], default=0),
        ),
    ]
