# Generated by Django 3.0.1 on 2020-01-02 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_auto_20200102_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinformation',
            name='female_spec',
        ),
        migrations.RemoveField(
            model_name='personinformation',
            name='male_spec',
        ),
        migrations.AddField(
            model_name='femalespec',
            name='belongs_to_person',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Person.PersonInformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malespec',
            name='belongs_to_person',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Person.PersonInformation'),
            preserve_default=False,
        ),
    ]
