# Generated by Django 3.0.1 on 2020-01-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ONEUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(0, 'No_access'), (1, 'Agent'), (2, 'Director'), (3, 'Manager'), (4, 'Admin')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('last_login', models.TimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
